name: PipelineWorkflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
     name: Azure Pipeline
     runs-on: windows-latest
     steps:
     - name: Azure Pipeline Action
       uses: Azure/piplines@v1
       with:
         azure-devops-project-url: https://dev.azure.com/ronaldcyu/DevProject
         azure-pipeline-name: 'RonaldYu.gitapp'
         azure-pipeline-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}