name: PipelineWorkflow

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipeline Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/ronaldcyu/DevProject
            azure-pipeline-name: 'RonaldYu.gitapp'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}